config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  # ユーザー用
  devise_for :users, skip: [:passwords], controllers: {
    registrations: 'user/registrations',
    sessions: 'user/sessions'
  }
  devise_scope :user do
    post 'users/guest_sign_in', to: 'user/sessions#guest_sign_in'
  end
  get 'searches/search'

  scope module: :user do
    root to: 'homes#top'
    post 'like/:id' => 'likes#create', as: 'create_like'
    delete 'like/:id' => 'likes#destroy', as: 'destroy_like'
    get 'users/about' => 'homes#about', as: 'about'
    get 'users/mypage' => 'users#show', as: 'mypage'
    get 'users/information/edit' => 'users#edit', as: 'edit_information'
    patch 'users/information' => 'users#update', as: 'update_information'
    get 'users/quit' => 'users#quit', as: 'confirm_quit'
    put 'users/information' => 'users#update'
    patch 'users/out' => 'users#out', as: 'out_user'
    resources :reservations
    resources :rooms, only: %i[index show]
    resource :message, only: :create
    resources :posts, only: %i[index show] do
      resources :comments, only: %i[create destroy]
    end
  end
  # サロン用
  devise_for :salons, skip: [:passwords], controllers: {
    registrations: 'salon/registrations',
    sessions: 'salon/sessions'
  }

  namespace :salon do
    root to: 'homes#top'
    get 'users/:user_id/resarvations' => 'resarvations#index', as: 'user_resarvations'
    get 'salons/mypage' => 'salons#show', as: 'mypage'
    get 'salons/information/edit' => 'salons#edit', as: 'edit_information'
    patch 'salons/information' => 'salons#update', as: 'update_information'
    get 'salons/quit' => 'salons#quit', as: 'confirm_quit'
    put 'salons/information' => 'salons#update'
    patch 'salons/out' => 'salons#out', as: 'out_salon'
    resources :posts, only: %i[index show new create edit update destroy]
    resources :comments, only: %i[index show destroy]
    resources :reservations
    resources :users, only: %i[show index edit update]
    resources :rooms, only: %i[index show]
    resource :message, only: :create
  end
end

app/models/post.rb
class Post < ApplicationRecord
  has_one_attached :image
  belongs_to :salon, optional: true
  has_many :comments, dependent: :destroy
  has_many :read_counts, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :tags, dependent: :destroy

  def get_image(width, height)
    image.variant(resize_to_limit: [width, height]).processed
  end

  validates :title, presence: true
  validates :body, presence: true
  validates :image, presence: true

  scope :latest, -> { order(created_at: :desc) }
  scope :old, -> { order(created_at: :asc) }
  scope :like_count, -> { order(like: :desc) }
end

app/models/salon.rb
class Salon < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :menus, dependent: :destroy
  has_many :posts, dependent: :destroy
  has_many :messages, dependent: :destroy

  validates :name, presence: true
  validates :introduction, presence: true
  validates :email, presence: true, uniqueness: true
  validates :postal_code, presence: true, format: { with: /\A\d{7}\z/ }
  validates :address, presence: true
  validates :phone_number, presence: true, format: { with: /\A\d{10,11}\z/ }
end

app/controllers/salon/comments_controller.rb
class Salon::CommentsController < ApplicationController
  before_action :authenticate_salon!
  def index
    @comments = Comment.page(params[:page]).per(10)
    @post = Post.find_by(params[:id])
  end

  def show
    @comment = Comment.find(params[:id])
    @post = Post.find_by(params[:id])
  end

  def destroy
    Comment.find(params[:id]).destroy
    redirect_to salon_comments_path(params[:post_id]), notice: '不適切なコメントを削除しました。'
  end

  private

  def comment_params
    params.require(:comment).permit(:content, :post_id, :user_id)
  end
end

app/controllers/salon/confirmations_controller.rb
# frozen_string_literal: true

class Salon::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/salon/homes_controller.rb
class Salon::HomesController < ApplicationController
  before_action :authenticate_salon!
  def top
    @now = Date.today.month
    @reserve = Reservation.where('created_at >= ?', Date.today)
    @salon = current_salon
  end
end

app/controllers/salon/messages_controller.rb
class Salon::MessagesController < ApplicationController
  before_action :authenticate_salon!
  def create
    message = Message.new(message_params)
    if message.save
      flash[:success] = 'メッセージを送信しました'
      redirect_to salon_room_path(message.room.reservation_id)
    else
      flash[:danger] = 'メッセージを送信できませんでした'
      redirect_to salon_room_path(message.room.reservation_id)
    end
  end

  private

  def message_params
    params.require(:message).permit(:message, :room_id).merge(salon_id: current_salon.id)
  end
end

app/controllers/salon/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Salon::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/salon/passwords_controller.rb
# frozen_string_literal: true

class Salon::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/salon/posts_controller.rb
class Salon::PostsController < ApplicationController
  before_action :authenticate_salon!
  def index
    @posts = if params[:latest]
               Post.latest.page(params[:page]).per(5)
             elsif params[:old]
               Post.old.page(params[:page]).per(5)
             elsif params[:like_count]
               Post.left_joins(:likes).group(:id).order('COUNT(likes.id) DESC').page(params[:page]).per(5)
             else
               Post.all.order(created_at: 'desc').page(params[:page]).per(5)
             end
  end

  def show
    @post = Post.find(params[:id])
    @comment = Comment.new
    @post_comments = @post.comments
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    if @post.save
      tags = Vision.get_image_tag(@post.image) # @post.imageを渡す
      tags.each do |tag|
        @post.tags.create(name: tag)
      end
      flash[:success] = '投稿が完了しました'
      redirect_to salon_post_path(@post.id)
    else
      flash.now[:danger] = '投稿に失敗しました'
      render :new
    end
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])
    tags = Vision.get_image_tag(@post.image)
    # 既存のタグを削除
    @post.tags.destroy_all
    # 新しいタグを追加
    tags.each do |tag|
      @post.tags.create(name: tag)
    end
    if @post.update(post_params)
      flash[:success] = '投稿を編集しました'
      redirect_to salon_post_path(@post)
    else
      flash.now[:danger] = '編集に失敗しました'
      render :edit
    end
  end

  def destroy
    post = Post.find(params[:id])
    post.destroy
    flash[:success] = '投稿を削除しました'
    redirect_to salon_posts_path
  end

  private

  def post_params
    params.require(:post).permit(:title, :body, :image)
  end
end

app/controllers/salon/registrations_controller.rb
# frozen_string_literal: true

class Salon::RegistrationsController < Devise::RegistrationsController
  before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]
  def after_sign_up_path_for(_resource)
    salon_mypage_path
  end
  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
  def configure_sign_up_params
    devise_parameter_sanitizer.permit(:sign_up,
                                      keys: %i[name introduction email postal_code address phone_number])
  end
end

app/controllers/salon/reservations_controller.rb
class Salon::ReservationsController < ApplicationController
  before_action :authenticate_salon!
  def index
    @reservations = Reservation.all
  end

  def show
    @reservation = Reservation.find(params[:id])
  end

  def edit
    @reservation = Reservation.find_by(params[:id])
  end

  def update
    @reservation = Reservation.find(params[:id])
    if @reservation.update(reservation_params)
      flash[:success] = '予約を変更しました'
      redirect_to salon_reservation_path(@reservation)
    else
      flash.now[:danger] = '変更に失敗しました'
      render :edit
    end
  end

  def destroy
    @reservation = Reservation.find(params[:id])
    if @reservation.destroy
      flash[:success] = '予約を削除しました'
      redirect_to salon_reservations_path(@reservation)
    else
      flash[:success] = '予約の削除に失敗しました'
      render :index
    end
  end

  private

  def reservation_params
    params.require(:reservation).permit(:day, :time, :user_id, :start_time)
  end
end

app/controllers/salon/rooms_controller.rb
class Salon::RoomsController < ApplicationController
  before_action :authenticate_salon!
  before_action :set_room, only: :show

  def index
    @reservations = Reservation.includes(:user).order(day: 'DESC').all.page(params[:page]).per(10)
  end

  def show
    @message = Message.new
    @messages = Message.where(room_id: @room.id)

    # 来店日を3日以上過ぎている予約判定の為、変数定義
    @close_reservation = @room.reservation if @room.reservation.day < Date.today - 2
  end

  private

  def set_room
    # 予約に紐づくルームを@roomに定義
    @room = Room.find_by(reservation_id: params[:id])

    # roomが存在するか判定し、存在しない場合にreservation_idを渡して作成する
    return unless @room.nil?

    @room = Room.new(reservation_id: params[:id])
    redirect_to rooms_path, alert: 'メッセージルームに入れませんでした' unless @room.save
  end
end

app/controllers/salon/salons_controller.rb
class Salon::SalonsController < ApplicationController
  before_action :authenticate_salon!
  before_action :set_current_salon

  def show; end

  def edit; end

  def update
    if @salon.update(salon_params)
      flash[:success] = 'サロン情報を更新しました'
      redirect_to salon_mypage_path
    else
      flash[:danger] = 'サロン情報の更新に失敗しました'
      render :edit
    end
  end

  def quit; end

  def out; end

  private

  def set_current_salon
    @salon = current_salon
  end

  def salon_params
    params.require(:salon).permit(:name, :introduction, :email, :postal_code, :address, :phone_number)
  end
end

app/controllers/salon/sessions_controller.rb
# frozen_string_literal: true

class Salon::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]
  def after_sign_in_path_for(_resource)
    salon_mypage_path
  end
  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/salon/unlocks_controller.rb
# frozen_string_literal: true

class Salon::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/salon/users_controller.rb
class Salon::UsersController < ApplicationController
  before_action :authenticate_salon!
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    @user_reservations = @user.reservation.where('start_time >= ?', DateTime.current).order(day: :desc)
    @visit_historys = @user.reservation.where('start_time < ?', DateTime.current).where('start_time > ?',
                                                                                        DateTime.current << 12).order(day: :desc)
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:success] = '会員情報を変更に成功しました'
      redirect_to salon_user_path(@user.id)
    else
      flash[:danger] = '会員情報の更新に失敗しました'
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:first_name, :last_name, :first_name_kana, :nick_name, :birthday, :last_name_kana,
                                 :postal_code, :address, :phone_number, :email, :is_deleted)
  end
end

app/controllers/user/posts_controller.rb
class User::PostsController < ApplicationController
  def index
    @comment = Comment.new
    if params[:latest]
      @posts = Post.latest.page(params[:page]).per(5)
    elsif params[:old]
      @posts = Post.old.page(params[:page]).per(5)
    elsif params[:like_count]
      @posts = Post.left_joins(:likes).group(:id).order('COUNT(likes.id) DESC').page(params[:page]).per(5)
    else
      @posts = Post.all.order(created_at: 'desc').page(params[:page]).per(5)
    end
  end

  def show
    @post = Post.find(params[:id])
    unless ReadCount.where(created_at: Time.zone.now.all_day).find_by(user_id: current_user.id, post_id: @post.id)
      current_user.read_counts.create(post_id: @post.id)
    end
    @comment = Comment.new
    @post_comments = @post.comments
  end
end

app/controllers/user/salons_controller.rb
class User::SalonsController < ApplicationController
  def index
    @salons = Salon.all
  end
end

app/helpers/salon/comments_helper.rb
module Salon::CommentsHelper
end

app/helpers/salon/homes_helper.rb
module Salon::HomesHelper
end

app/views/salon/posts/edit.html.erb
        <!-- form_with部分 -->
        <%= form_with model: [:salon, @post], url: salon_post_path do |f| %>
  <div class="container my-5">
    <div class="row">
      <div class="col-10 mx-auto">
        <h5 class="ml-5 mb-5"><span class="title-custom px-4">投稿編集 <i class="fa-solid fa-pen-to-square"></i></span></h5>
          <table class="table table-borderless">
            <%= render 'layouts/error', obj: @post %>
              <div class="col-8 mx-auto form-group">
                <tr>
                  <td>商品画像</td>
                  <td><%= f.file_field :image, accept: "image/*" %></td>
                </tr>
                <tr>
                  <td>タイトル</td>
                  <td> <%= f.text_field :title, placeholder:"タイトルを入力してください", class: "form-control" %></td></tr>
                <tr>
                  <td>内容</td>
                  <td> <%= f.text_area :body, :placeholder =>"#{@post.body}", class: "form-control"%></td>
                </tr>
                  <!--登録ボタン-->
                  <td><%= f.submit '変更内容を保存する' ,class:"btn btn-success" %></td>
          </table>
        <% end %>
              </div>
      </div>
    </div>
  </div>

app/views/salon/posts/index.html.erb
<div class="container">
  <div class="row pt-5">
    <div class="col-12 text-center title">
      <h4>Blog <i class="fa-brands fa-instagram"></i></h4></div>
        <%= link_to new_salon_post_path, class: "btn btn-outline-info" do%>
          追加
          <i class="fa-solid fa-square-plus"></i>
        <% end %>
          <div class="col-12 text-center title">
            <%= link_to '新しい順',salon_posts_path(latest: "true") %> |
            <%= link_to '古い順', salon_posts_path(old: "true") %> |
            <%= link_to 'いいね件数順', salon_posts_path(like_count: "true") %>
          </div>
            <table class='table table-hover table-inverse'>
              <thead>
                <tr>
                  <th></th>
                  <th>Title</th>
                  <th>Date</th>
                  <th colspan="3"></th>
                </tr>
              </thead>
              <tbody>
                <% @posts.each do |post| %>
                <tr>
                <td>
                  <%= link_to salon_post_path(post.id) do %>
                    <%= image_tag post.image, size: "250x280" , class: "shadow p-3 mb-5 bg-white", style: "margin: auto;" %>
                  <% end %>
                </td>
                <td><%= link_to post.title, salon_post_path(post) %></td>
                <td><%= post.created_at.strftime("%Y年%m月%d日(%a)")%></td>
                <td>
                <i class="fa fa-heart like"></i>
                <%= post.likes.count %></td>
                <td><i class="fa-regular fa-comment">
               <%= post.comments.count %></td>
              </tr>
                <%end%>
              </tbody>
          </table>
  </div>
</div>
<%= paginate @posts %>

app/views/salon/posts/new.html.erb
       <%= form_with model: @post, url: salon_posts_path, method: :post, enctype: "multipart/form-data" do |f| %>
  <div class="container new-post-container my-5">
    <div class="row">
      <div class="col-10 mx-auto">
        <h5 class="ml-5 mb-5"><span class="title-custom px-4">New Post <i class="fa-solid fa-file-circle-plus"></i></span></h5>
        <table class="table table-borderless new-post-table">
          <%= render 'layouts/error', obj: @post %>
          <div class="col-8 mx-auto form-group">
            <tr>
              <td>画像</td>
              <td><%= f.file_field :image, accept: "image/*" %></td>
            </tr>
            <tr>
              <td>タイトル</td>
              <td><%= f.text_field :title, placeholder: "投稿タイトルを入力してください", class: "form-control" %></td>
            </tr>
            <tr>
              <td>内容</td>
              <td><%= f.text_area :body, placeholder: "内容を入力してください", class: "form-control" %></td>
            </tr>
            <!-- 登録ボタン -->
            <tr>
              <td colspan="2"><%= f.submit '新規登録', class: "btn btn-success" %></td>
            </tr>
          </table>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/salon/posts/show.html.erb
<div class="container post-detail-container">
  <div class="col-md-12 mx-auto mt-5">
    <div class="row justify-content-center mb-5">
      <h4>Post Detail <i class="fa-regular fa-image"></i></h4>
    </div>
  </div>
    <div class="col-md-5 mx-auto mt-5">
      <div class="row d-flex justify-content-center">
        <div class="col-12 d-flex text-center justify-content-center align-items-center">
          <%= image_tag @post.image, size: "300x330" %>
        </div>
          <div class="tag-box">
            <% @post.tags.each do |tag| %>
              <span class="label">#<%= tag.name %></span>
            <% end %>
          </div>
      </div>
    </div>
      <div class="col-12 text-center title">
        <i class="fa-regular fa-comment"></i><span id="comment_count"><%= @post.comments.count %></span>commnts
          <i class="fa-regular fa-eye"></i><%= @post.read_counts.count %>views
            <span> <i class="fa fa-heart like"></i>
              <%= @post.likes.count %></span>
        </div>
          <div class="col-8 mx-auto mt-5 ">
            <div class="box73">
              <div class="box-title"><%= @post.title%>
              </div>
                <%= @post.body %>
            </div>
          </div>
    <div class=" mt-3 text-center">
      <%= link_to "編集", edit_salon_post_path(@post.id), class: "btn w-25 mt-3 change_button", style: "background-color:#8fbc8f;" %>
        <%= link_to "削除", @posts, method: :delete, "data-confirm" => "本当に削除しますか？" ,class: "btn w-25 mt-3 change_button", style: "background-color:#cd5c5c;"%>
    </div>
  <div id="comments-area"><%= render "salon/comments/comment", post: @post,comment: @comment,post_comments: @post_comments %>
  </div>
</div>