config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  # ユーザー用
  devise_for :users, skip: [:passwords], controllers: {
    registrations: 'user/registrations',
    sessions: 'user/sessions'
  }
  devise_scope :user do
    post 'users/guest_sign_in', to: 'user/sessions#guest_sign_in'
  end
  get 'searches/search'

  scope module: :user do
    root to: 'homes#top'
    post 'like/:id' => 'likes#create', as: 'create_like'
    delete 'like/:id' => 'likes#destroy', as: 'destroy_like'
    get 'users/about' => 'homes#about', as: 'about'
    get 'users/mypage' => 'users#show', as: 'mypage'
    get 'users/information/edit' => 'users#edit', as: 'edit_information'
    patch 'users/information' => 'users#update', as: 'update_information'
    get 'users/quit' => 'users#quit', as: 'confirm_quit'
    put 'users/information' => 'users#update'
    patch 'users/out' => 'users#out', as: 'out_user'
    resources :reservations
    resources :rooms, only: %i[index show]
    resource :message, only: :create
    resources :posts, only: %i[index show] do
      resources :comments, only: %i[create destroy]
    end
  end
  # サロン用
  devise_for :salons, skip: [:passwords], controllers: {
    registrations: 'salon/registrations',
    sessions: 'salon/sessions'
  }

  namespace :salon do
    root to: 'homes#top'
    get 'users/:user_id/resarvations' => 'resarvations#index', as: 'user_resarvations'
    get 'salons/mypage' => 'salons#show', as: 'mypage'
    get 'salons/information/edit' => 'salons#edit', as: 'edit_information'
    patch 'salons/information' => 'salons#update', as: 'update_information'
    get 'salons/quit' => 'salons#quit', as: 'confirm_quit'
    put 'salons/information' => 'salons#update'
    patch 'salons/out' => 'salons#out', as: 'out_salon'
    resources :posts, only: %i[index show new create edit update destroy]
    resources :comments, only: %i[index show destroy]
    resources :reservations
    resources :users, only: %i[show index edit update]
    resources :rooms, only: %i[index show]
    resource :message, only: :create
  end
end

app/controllers/salon/users_controller.rb
class Salon::UsersController < ApplicationController
  before_action :authenticate_salon!
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    @user_reservations = @user.reservation.where('start_time >= ?', DateTime.current).order(day: :desc)
    @visit_historys = @user.reservation.where('start_time < ?', DateTime.current).where('start_time > ?',
                                                                                        DateTime.current << 12).order(day: :desc)
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:success] = '会員情報を変更に成功しました'
      redirect_to salon_user_path(@user.id)
    else
      flash[:danger] = '会員情報の更新に失敗しました'
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:first_name, :last_name, :first_name_kana, :nick_name, :birthday, :last_name_kana,
                                 :postal_code, :address, :phone_number, :email, :is_deleted)
  end
end

app/controllers/user/comments_controller.rb
class User::CommentsController < ApplicationController
  before_action :authenticate_user!
  before_action :ensure_correct_user, only: [:destroy]
  def create
    @post = Post.find(params[:post_id])
    @post_comments = @post.comments
    @comment = Comment.new(comment_params)
    @comment.user_id = current_user.id
    @comment.post_id = @post.id
    @comment.score = Language.get_comment(comment_params[:content])
    @comment.save
    flash[:success] = 'コメントしました'
  end

  def destroy
    @post = Post.find(params[:post_id])
    @post_comments = @post.comments
    @comment = Comment.find(params[:id])
    @comment.destroy
    flash[:success] = 'コメントを削除しました'
  end

  private

  def ensure_correct_user
    @comment = Comment.find(params[:id])
    return if @comment.user == current_user

    redirect_to posts_path, notice: '投稿者以外コメントは削除できません。'
  end

  def comment_params
    params.require(:comment).permit(:content)
  end
end

app/controllers/user/confirmations_controller.rb
# frozen_string_literal: true

class User::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/user/homes_controller.rb
class User::HomesController < ApplicationController
  def top
    @posts = Post.order('id DESC').limit(2)
  end

  def about
    @salon = Salon.find_by(params[:id])
  end
end

app/controllers/user/likes_controller.rb
class User::LikesController < ApplicationController
  before_action :authenticate_user!
  before_action :post_params
  def create
    Like.create(user_id: current_user.id, post_id: params[:id])
  end

  def destroy
    Like.find_by(user_id: current_user.id, post_id: params[:id]).destroy
  end

  private

  def post_params
    @post = Post.find(params[:id])
  end
end

app/controllers/user/messages_controller.rb
class User::MessagesController < ApplicationController
  before_action :authenticate_user!
  def create
    message = Message.new(message_params)
    if message.save
      flash[:success] = 'メッセージを送信しました'
      redirect_to room_path(message.room.reservation_id)
    else
      flash[:danger] = 'メッセージを送信できませんでした'
      redirect_to room_path(message.room.reservation_id)
    end
  end

  private

  def message_params
    params.require(:message).permit(:message, :room_id).merge(user_id: current_user.id)
  end
end

app/controllers/user/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class User::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/user/passwords_controller.rb
# frozen_string_literal: true

class User::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/user/posts_controller.rb
class User::PostsController < ApplicationController
  def index
    @comment = Comment.new
    if params[:latest]
      @posts = Post.latest.page(params[:page]).per(5)
    elsif params[:old]
      @posts = Post.old.page(params[:page]).per(5)
    elsif params[:like_count]
      @posts = Post.left_joins(:likes).group(:id).order('COUNT(likes.id) DESC').page(params[:page]).per(5)
    else
      @posts = Post.all.order(created_at: 'desc').page(params[:page]).per(5)
    end
  end

  def show
    @post = Post.find(params[:id])
    unless ReadCount.where(created_at: Time.zone.now.all_day).find_by(user_id: current_user.id, post_id: @post.id)
      current_user.read_counts.create(post_id: @post.id)
    end
    @comment = Comment.new
    @post_comments = @post.comments
  end
end

app/controllers/user/registrations_controller.rb
# frozen_string_literal: true

class User::RegistrationsController < Devise::RegistrationsController
  before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]
  def after_sign_up_path_for(_resource)
    mypage_path
  end
  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end

  def configure_sign_up_params
    devise_parameter_sanitizer.permit(:sign_up,
                                      keys: %i[first_name last_name first_name_kana last_name_kana nick_name birthday profile_image postal_code
                                               address phone_number])
  end
end

app/controllers/user/reservations_controller.rb
class User::ReservationsController < ApplicationController
  before_action :authenticate_user!

  def index
    @reservations = Reservation.all.where('day >= ?', Date.current).where('day < ?',
                                                                          Date.current >> 3).order(day: :desc)
  end

  def new
    @reservation = Reservation.new
    @day = params[:day]
    @time = params[:time]
    @start_time = DateTime.parse(@day + ' ' + @time + ' ' + 'JST')
    message = Reservation.check_reservation_day(@day.to_date)
    return unless !!message

    redirect_to @reservation, flash: { alert: message }
  end

  def show
    @reservation = Reservation.find(params[:id])
  end

  def create
    @reservation = Reservation.new(reservation_params)

    # 既存の予約を取得
    existing_reservations = Reservation.where(user_id: current_user.id)

    # 予約可能かどうかチェック
    if existing_reservations.any? { |existing| existing.start_time > Time.now }
      flash[:danger] = '既存の予約があります。予約時間を過ぎるか、既存の予約をキャンセルしてから新しい予約を取ってください。'
      render :new
    elsif @reservation.save
      flash[:success] = '予約が完了しました'
      redirect_to reservation_path @reservation.id
    else
      flash[:danger] = '予約に失敗しました'
      render :new
    end
  end

  def edit
    @reservation = Reservation.find_by(params[:id])
  end

  def update
    @reservation = Reservation.find(params[:id])
    if @reservation.update(reservation_params)
      flash[:success] = '予約を変更しました'
      redirect_to salon_reservation_path(@reservation)
    else
      flash.now[:danger] = '変更に失敗しました'
      render :edit
    end
  end

  private

  def reservation_params
    params.require(:reservation).permit(:day, :time, :user_id, :start_time)
  end
end

app/controllers/user/rooms_controller.rb
class User::RoomsController < ApplicationController
  before_action :authenticate_user!
  before_action :get_two_days_ago
  before_action :set_room_or_move, only: :show

  def index
    # 今日から2日前以降の予約を取得
    @reservation = current_user.reservation.where('day >= ?', @two_days_ago).order(day: 'DESC')
  end

  def show
    move_to_index_for_expired
    @message = Message.new
    @messages = Message.where(room_id: @room.id)
  end

  private

  def get_two_days_ago
    @two_days_ago = Date.today - 2
  end

  def set_room_or_move
    # ログインユーザーの予約に紐づくルームへのアクセスでない場合、リダイレクト
    redirect_to rooms_path, alert: 'メッセージルームに入れませんでした' if Reservation.find(params[:id]).user_id != current_user.id

    # 予約に紐づくルームを@roomに定義
    @room = Room.find_by(reservation_id: params[:id])

    # roomが存在するか判定し、存在しない場合にreservation_idを渡して作成する
    return unless @room.nil?

    @room = Room.new(reservation_id: params[:id])
    redirect_to rooms_path, alert: 'メッセージルームに入れませんでした' unless @room.save
  end

  def move_to_index_for_expired
    # 来店日を３日間以降過ぎている場合、ルーム一覧へリダイレクト
    return unless @room.reservation.day < @two_days_ago

    redirect_to rooms_path and return
  end
end

app/controllers/user/salons_controller.rb
class User::SalonsController < ApplicationController
  def index
    @salons = Salon.all
  end
end

app/controllers/user/sessions_controller.rb
# frozen_string_literal: true

class User::SessionsController < Devise::SessionsController
  before_action :reject_inactive_user, only: [:create]
  # before_action :configure_sign_in_params, only: [:create]
  def after_sign_in_path_for(_resource)
    mypage_path
  end
  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected
  def reject_inactive_user
    @user = User.find_by(email: params[:user][:email])
    return unless @user
    return unless @user.valid_password?(params[:user][:password]) && @user.is_deleted

    flash[:danger] = 'お客様は退会済みです。申し訳ございませんが、別のメールアドレスをお使いください。'
    redirect_to new_user_session_path
  end

  def guest_sign_in
    user = User.guest
    sign_in user
    redirect_to root_path, notice: 'ゲストユーザーとしてログインしました。'
  end
  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/user/unlocks_controller.rb
# frozen_string_literal: true

class User::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/user/users_controller.rb
class User::UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :set_current_user
  before_action :ensure_guest_user, only: [:edit]
  
  def show
    @user_reservations = current_user.reservation.where('start_time >= ?', DateTime.current).order(day: :desc)
    @visit_historys = current_user.reservation.where('start_time < ?', DateTime.current).where('start_time > ?',
                                                                                               DateTime.current << 12).order(day: :desc)
  end

  def edit; end

  def update
    if @user.update(user_params)
      flash[:success] = '会員情報を更新しました'
      redirect_to mypage_path
    else
      flash[:danger] = '会員情報の更新に失敗しました'
      render :edit
    end
  end

  def quit; end

  def out
    @user.update(is_deleted: true)
    reset_session
    redirect_to root_path
  end

  def destroy_confirm
    @user = current_user
  end

  def destroy_user
    @user = current_user
    if @user.email == 'guestda@example.com'
      reset_session
      redirect_to :root
    else
      @user.update(is_valid: false)
      reset_session
      redirect_to :root
    end
  end

  private

  def set_current_user
    @user = current_user
  end
  
  def ensure_guest_user
    @user = current_user
    if @user.guest_user?
      redirect_to mypage_path(current_user) , notice: "ゲストユーザーはプロフィール編集画面へ遷移できません。"
    end
  end  

  def user_params
    params.require(:user).permit(:last_name, :first_name, :first_name_kana, :last_name_kana, :nick_name, :birthday,
                                 :profile_image, :email, :postal_code, :address, :phone_number)
  end
end

app/helpers/salon/users_helper.rb
module Salon::UsersHelper
end

app/helpers/user/homes_helper.rb
module User::HomesHelper
end

app/helpers/user/messages_helper.rb
module User::MessagesHelper
end

app/views/user/users/edit.html.erb
<!-- form_with部分 -->
<%= form_with model: @user, url: update_information_path do |f| %>
  <div class="container user-edit-container my-5">
    <div class="row">
      <div class="col-10 mx-auto">
        <h5 class="ml-5 mb-5"><span class="title-custom px-4">マイページ編集</span></h5>
          <table class="table table-borderless user-edit-table">
            <%= render 'layouts/error', obj: @user%>
              <div class="col-8 mx-auto form-group">
            <tr>
              <td><%= f.label :inmage,"プロフィール画像" %></td>
              <td><%= f.file_field :profile_image, placeholder: "プロフィール画像", accept: "image/*",:placeholder =>"#{@user.get_profile_image(100,100)}" %>  </td>
            </tr>
            <tr>
              <td>名前</td>
              <td><%= f.label :last_name, "(姓)",class: "user_name" %><%= f.text_field :last_name, :placeholder =>"#{@user.last_name}" %></td>
              <td><%= f.label :first_name, "(名)", class: "user_name" %> <%= f.text_field :first_name, :placeholder =>"#{@user.first_name}" %></td>
            </tr>
            <tr>
              <td>フリガナ</td>
              <td><%= f.label :last_name_kana, "(セイ)" %><%= f.text_field :last_name_kana, :placeholder =>"#{@user.last_name_kana}" %></td>
              <td><%= f.label :first_name_kana, "(メイ)" %><%= f.text_field :first_name_kana, :placeholder =>"#{@user.first_name_kana}" %></td></tr>
            <tr>
            <tr>
              <td><%= f.label :nick_name,"ニックネーム" %></td>
              <td colspan="2"><%= f.text_field :nick_name, :placeholder =>"#{@user.nick_name}" %></td>
            </tr>
            <tr>
              <td><%= f.label :birthday,"生年月日" %></td>
              <td colspan="2"><%= f.date_select :birthday, {start_year: 1950, end_year: 2016,include_blank: true, use_two_digit_numbers: true},
                              {class: "input-tab birthday-select"} %></td>
            </tr>
              <td><%= f.label :email,"メールアドレス" %></td>
              <td colspan="2"><%= f.email_field :email, autocomplete: "email",:placeholder =>"#{@user.email}" %></td>
            </tr>
            <tr>
              <td><%= f.label :postal_code, "郵便番号(ハイフンなし7桁)" %></td>
              <td colspan="2"><%= f.text_field :postal_code, :placeholder =>"#{@user.postal_code}", class: "jpostal_code" %></td>
            </tr>
            <tr>
              <td><%= f.label :address, "住所"%></td>
              <td colspan="2"><%= f.text_field :address, :placeholder =>"#{@user.address}",class: "jpostal_address" %></td>
            </tr>
            <tr>
              <td><%= f.label :phone_number, "電話番号(ハイフン無し10 or 11桁)" %></td>
              <td colspan="2"><%= f.text_field :phone_number, :placeholder =>"#{@user.phone_number}" %></td>
            </tr>
              <!--登録ボタン-->
              <td><%= f.submit '編集内容を保存する' ,class:"btn btn-success" %></td>
              <td><%= link_to "退会する", confirm_quit_path, class: "btn btn-danger" %></td>
          </table>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/user/users/quit.html.erb
<div class="container my-5">
  <div class="row">
    <div class="col-12 mx-auto">
<h3 class="section-ttl">本当に退会しますか？</h3>
  <h4 class="text-center"><i class="fa-solid fa-triangle-exclamation"></i> 退会すると、サロン情報の閲覧や<br>予約ができなくなります。<br>退会する場合は、「退会する」をクリックしてください。</h4>
    <div class= "text-center">
      <%= link_to "マイページに戻る", mypage_path, class: "btn btn-info" %>
        <%= link_to "退会する", out_user_path, method: :patch, "data-confirm" => "OKを押すと退会処理がされます。本当によろしいですか？", class: "btn btn-danger" %>
    </div>
    </div>
  </div>
</div>

app/views/user/users/show.html.erb
<div class = "container my-4">
  <h4><strong style="background-color:#EEEEEE;">My page<i class="fa-regular fa-user"></i></strong></h4>
    <% unless @user.guest_user? %>
      <div class = "row">
        <%= link_to "編集する", edit_information_path, class: "btn d-flex align-items-center ms-3", style: "background-color: #dda0dd; color: #fffafa" %>
      </div>
    <% end %>
    <div class='row'>
      <table class="table table-bordered border-dark table-hover table-inverse custom-table">
        <tbody>
          <tr>
              <th>プロフィール画像</th>
               <td><%= image_tag @user.get_profile_image(100,100) %></td>
         </tr>
          <tr>
              <th>氏名</th>
               <td><%= @user.last_name %>
          <%= @user.first_name %></td>
         </tr>
         <tr>
              <th>カナ</th>
               <td><%= @user.last_name_kana %>
              <%= @user.first_name_kana %></td>
         </tr>
         <tr>
              <th>ニックネーム</th>
               <td><%= @user.nick_name %></td>
         </tr>
         <tr>
              <th>生年月日</th>
               <td><%= @user.birthday %></td>
         </tr>
         <tr>
              <th>メールアドレス</th>
               <td><%= @user.email %></td>
         </tr>
         <tr>
              <th>電話番号</th>
               <td><%= @user.phone_number %></td>
         </tr>
         <tr>
              <th>郵便番号</th>
               <td><%= @user.postal_code %></td>
         </tr>
         <tr>
              <th>住所</th>
               <td><%= @user.address %></td>
         </tr>
          <div class="col-12 mt-3 text-center mx-auto">

        <table class="table">
          <thead>
            <tr>
              <th scope="col">予約日</th>
              <th></th>
            </tr>
          </thead>
          <tbody>
            <% @user_reservations.each do |user_reservation| %>
              <td>
                <%=  user_reservation.day.strftime("%Y年%m月%d日(%a)") %><%=  user_reservation.time.strftime("%H:%M") %>
              </td>
            </tr>
            <% end %>
            <% if @user_reservations.blank? %>
              <tr>
                <td>予約はありません。</td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
      <div class="col-12 mt-3 text-center mx-auto">
        <h3>来院履歴</h3>
        <table class="table">
          <thead>
            <tr>
              <th scope="col">予約日</th>
            </tr>
          </thead>
          <tbody>
            <% @visit_historys.each do |visit_history| %>
              <tr>
                <td>
                  <%=  visit_history.day.strftime("%Y年%m月%d日(%a)") %><%=  visit_history.time.strftime("%H:%M") %>
                </td>
              </tr>
            <% end %>
            <% if @visit_historys.blank? %>
              <tr>
                <td>来院履歴はありません。</td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
        </tbody>
      </table>
</div>